server:
  port: 9090 #后端运行端口

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动不变
    url: jdbc:mysql://localhost:3306/own?useSSL=false&Timezone=GMT%2B8 # own 的变成自己的数据库名
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


files:
  upload:
    path: D:/Code/ownP/files/  #储存上次的文件图片视频的储存位置，自己可以改成逻辑地址
